### ISSUE TITLE
too many input argument

### ISSUE THREAD

**Issue by hrheydarian** [imphys/smlm_classification2d#1]
Hi Teun,

It seems that there is something wrong here. In this file, the function [`outlier_removal_class`](https://github.com/imphys/smlm_classification2d/blob/master/matlab_functions/outlier_removal_class.m) is called with three input arguments. However, the function seems to need only two and the first argument has been removed previously although in function description it is still there.
https://github.com/imphys/smlm_classification2d/blob/b5cbe60c9915d0b93c8c6c5456722bc31da9efd8/matlab_functions/reconstructPerClassFunction.m#L66

Could you please have a look at that?

Bests,
hamidreza

**Comment by TeunHuijben** [comment]
Hi Hamid,

Thank you for catching the bug! I have resolved the issue.
Please let me know whether it works for you now.

Best,
Teun
